# syntax=docker/dockerfile:1.7

FROM golang:1.26.5-alpine3.23 AS builder

RUN apk add --no-cache ca-certificates

ARG CGO_ENABLED=0
ARG SERVICE_VERSION=local-workspace
ARG TARGETOS=linux
ARG TARGETARCH=amd64

ENV GOTOOLCHAIN=local

WORKDIR /src

COPY go.mod go.sum ./service/
COPY --from=core go.mod go.sum ./core/
COPY --from=proto go.mod go.sum ./proto/

RUN go work init ./service ./core ./proto

ENV GOWORK=/src/go.work

RUN --mount=type=cache,target=/go/pkg/mod,sharing=locked \
    cd /src/service && go mod download

COPY . ./service/
COPY --from=core . ./core/
COPY --from=proto . ./proto/

RUN cd /src/service && \
    core_dir="$(go list -m -f '{{.Dir}}' github.com/invenlore/core)" && \
    proto_dir="$(go list -m -f '{{.Dir}}' github.com/invenlore/proto)" && \
    printf "local module github.com/invenlore/core -> %s\n" "$core_dir" && \
    printf "local module github.com/invenlore/proto -> %s\n" "$proto_dir" && \
    test "$core_dir" = "/src/core" && \
    test "$proto_dir" = "/src/proto"

RUN --mount=type=cache,target=/go/pkg/mod,sharing=locked \
    --mount=type=cache,target=/root/.cache/go-build,sharing=locked \
    mkdir -p /out && \
    cd /src/service && \
    CGO_ENABLED="$CGO_ENABLED" GOOS="$TARGETOS" GOARCH="$TARGETARCH" \
    go build -mod=readonly -trimpath -buildvcs=false -o /out/service .

RUN printf "%s" "$SERVICE_VERSION" > /out/version.txt

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

WORKDIR /app

COPY --from=builder /out/service ./service
COPY --from=builder /out/version.txt ./version.txt

COPY --from=ghcr.io/tarampampam/microcheck:1 /bin/httpcheck /bin/httpcheck

USER 65532:65532

HEALTHCHECK --interval=1m --timeout=5s --start-period=10s --retries=3 CMD ["/bin/httpcheck", "--port-env=HEALTH_PORT", "http://localhost/health"]

ENTRYPOINT ["/app/service"]
